app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function (Request $request) {
    return redirect('home');
   
   
});


/*
|--------------------------------------------------------------------------
| API routes
|--------------------------------------------------------------------------
*/
Route::group(['prefix' => 'api', 'namespace' => 'API'], function () {
    Route::group(['prefix' => 'v1'], function () {
    	Route::post('auth', 'AuthAPIController@authenticate');
        Route::post('forgotPassword', 'AuthAPIController@forgot');
        Route::post('user/register', 'UserAPIController@register');
        Route::post('cekparam', 'AuthAPIController@cekparam');

        Route::get('user/send', 'UserAPIController@sendemail');
    	Route::group(['middleware' => ['jwt.auth']], function () {
            require config('infyom.laravel_generator.path.api_routes');
        });
    });
});


Route::group(['prefix' => 'cobranding', 'namespace' => 'COBRANDING'], function () {
    Route::group(['prefix' => 'v1'], function () {
    	Route::post('auth', 'AuthAPIController@authenticate');
       
    	Route::group(['middleware' => ['jwt.auth']], function () {
            require config('infyom.laravel_generator.path.api_routes');
        });
    });
});

Route::get('/elfinder/tinymce','Barryvdh\Elfinder\ElfinderController@showTinyMCE4');

Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@logout');

// Registration Routes...
// Route::get('register', 'Auth\AuthController@getRegister');
// Route::post('register', 'Auth\AuthController@postRegister');

// Password Reset Routes...
Route::get('password/reset', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

Route::group(['middleware' => ['auth']], function () {

     Route::get('fileupload', [
        'as' => 'fileupload',
        'uses' => 'Barryvdh\Elfinder\ElfinderController@showPopup',
    ]);

    Route::group(['middleware' => ['role:admin']], function () {
    
    });
    // tampilkan sesudah login
	Route::get('home', 'HomeController@index');
 
    
    Route::resource('user/login', 'UserController@login');
    Route::resource('user', 'UserController');


    
  
    Route::get('user/{id}/enable','UserController@enable');
    Route::get('user/{id}/disable','UserController@disable');
    Route::get('user/{id}/notification','UserController@notification');
    Route::get('user/deposite','UserController@deposite');

  
    Route::resource('role', 'RoleController');
    
    Route::get('transaction/{id}/enable','TransactionController@enable');
	Route::get('transaction/{id}/disable','TransactionController@disable');
    
  
  
    Route::resource('device', 'DeviceController');
  

    Route::resource('menu', 'MenuController');
    Route::get('deposite/tes', 'DepositeController@tes');
    Route::get('deposite/jmldeposite', 'DepositeController@jmldeposite');
    Route::get('deposite/jmlwithdraw', 'DepositeController@jmlwithdraw');
    Route::get('deposite/jmluser', 'DepositeController@jmluser');
    Route::get('deposite/listuserdeposite', 'DepositeController@listuserdeposite');
    Route::get('deposite/listtabeldeposite', 'DepositeController@listtabeldeposite');
    Route::get('deposite/listuserwithdraw', 'DepositeController@listuserwithdraw');
    Route::get('deposite/listtabelwithdraw', 'DepositeController@listtabelwithdraw');

    Route::get('deposite/bankAdmin', 'DepositeController@bankAdmin');

    Route::get('deposite/listtabeluser', 'DepositeController@listtabeluser');
     Route::get('deposite/listuserkyc', 'DepositeController@listuserkyc');

    Route::get('deposite/konfirmasi', 'DepositeController@konfirmasi');
   
    
 
    Route::get('deposite/detailuser', 'DepositeController@detailuser');  
    Route::get('deposite/blokiruser', 'DepositeController@blokiruser');
    Route::get('deposite/bataluser', 'DepositeController@bataluser');
    Route::get('deposite/terimauser', 'DepositeController@terimauser');

//send
     Route::get('deposite/kirim', 'DepositeController@kirim');
     Route::get('deposite/batal', 'DepositeController@batal');
      Route::get('deposite/delete','DepositeController@delete');



     Route::get('deposite/updatenotivdep', 'DepositeController@updatenotivdep');
     Route::get('deposite/updatenotivdraw', 'DepositeController@updatenotivdraw');   
     Route::get('deposite/updatenotivuser', 'DepositeController@updatenotivuser');   
});

Route::resource('admin', 'AdminController');

/* --- transaksi --- */
//Route::resource('order', 'OrderController');


Route::resource('purchase', 'PurchaseController');
Route::resource('packet', 'PacketController');
Route::resource('register', 'UserController@getRegister');
Route::post('user/register', 'UserController@postRegister');
Route::resource('client', 'ClientController');
Route::get('email', 'EmailController@index');
Route::resource('transaction', 'TransactionController');
Route::resource('history', 'HistoryController');
Route::resource('bank', 'BankController');
Route::resource('generate', 'GenerateController');


Route::get('dashboard/getsaldo', 'DashboardController@getsaldo');
Route::get('dashboard/getlates', 'DashboardController@getlates');
Route::get('dashboard/jmldana', 'DashboardController@jmldana');
Route::get('dashboard/totcobranding', 'DashboardController@totcobranding');


Route::get('dashboard/totmember', 'DashboardController@totmember');
Route::get('dashboard/totissuer', 'DashboardController@totissuer');
Route::get('dashboard/totmerchant', 'DashboardController@totmerchant');
Route::resource('setting', 'SettingController');


Route::resource('promo', 'PostController');


Route::resource('activity', 'ActivityController');

Route::resource('post', 'PostController');

/* Routes Galih */
Route::post('setting/postSaldo', 'SettingController@postDeposit'); /* transaksi tambah saldo */
Route::post('setting/postKonfirmSaldo', 'SettingController@postKonfirmasi'); /* konfirmasi transaksi tambah saldo */


Route::get('setting/list', 'SettingController@listadmin'); /* setting admin */


Route::get('deposite/listtabelcobrand', 'DepositeController@listtabelcobrand'); /* list table co branding */
// Route::get('user/create', 'DepositeController@create'); /* list table co branding */
Route::post('user/postCobrand', 'DepositeController@postcobrand'); /* simpan data co branding */
Route::post('user/postHapusCo', 'DepositeController@posthapuscobrand'); /* hapus data co branding */
Route::post('user/postEditCo', 'DepositeController@posteditcobrand'); /* edit data co branding */
Route::get('user/detailcobrand/{id}', 'DepositeController@detailco'); /* detail co branding */

Route::get('deposite/listtabelmerchant', 'DepositeController@listtabelmerchant'); /* list table merchant */
Route::get('order', 'OrderController@index'); /* list table merchant */
Route::get('order/history', 'OrderController@history'); /* list table merchant */
Route::get('order/checkstatus', 'OrderController@checkstatus');
Route::get('order/printorder', 'OrderController@printorder');


Route::post('user/postmerchant', 'DepositeController@postmerchant'); /* simpan data merchant */
Route::post('user/postHapusmerchant', 'DepositeController@posthapusmerchant'); /* hapus data merchant */
Route::post('user/postEditmerchant', 'DepositeController@posteditmerchant'); /* edit data merchant */
Route::get('user/detailmerchant/{id}', 'DepositeController@detailmerchant'); /* detail merchant */

Route::get('issuer/dataissuer', 'DepositeController@getissuer'); /* list table issuer */
Route::post('user/postissuer', 'DepositeController@postissuer'); /* simpan data issuer */
Route::post('user/postHapusissuer', 'DepositeController@posthapusissuer'); /* hapus data issuer */
Route::post('user/postEditIssuer', 'DepositeController@posteditissuer'); /* edit data issuer */
Route::get('user/detailissuer/{id}', 'DepositeController@detailissuer'); /* detail issuer */

Route::get('issuer/depositissuer', 'DepositeController@DepositeIssuer');
Route::get('issuer/lisdeposit', 'DepositeController@listtableDeposit');
Route::get('issuer/detailDep', 'DepositeController@getdetailDeposit');
Route::post('issuer/konfirDep', 'DepositeController@konfirmasi_deposit');

Route::get('issuer/historytrans', 'DepositeController@historyTransaction');
Route::get('issuer/listhistorytrans', 'DepositeController@listhistoryTransaction');
Route::get('issuer/detailhistorytrans', 'DepositeController@detailhistoryTransaction');
/* End Of Routes Galih */

/* --- Cobranding API --- */

Route::resource('access', 'AccessController');
Route::post('access/login', 'AccessController@login');
Route::get('reset', 'AccessController@reset');

resources/views/admin/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Edit Profile</h1>
       
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($user, ['route' => ['admin.update', $user->id], 'method' => 'patch','enctype'=>'multipart/form-data']) !!}

                        @include('admin.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/admin/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-12">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control', "placeholder" => "Name"]) !!}
    
    {!! Form::hidden('client_id', '0', ['class' => 'form-control']) !!} 
</div>


<div class="form-group col-sm-12">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control','placeholder' => 'Phone']) !!}
</div>



<div class="form-group col-sm-12">
    {!! Form::label('address', 'Address:') !!}
    {!! Form::textarea('address', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-12">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control',"placeholder" => "Email"]) !!}
</div>
        @if(!empty($user->password))
        <div class="form-group col-sm-12">
              {!! Form::label('password', 'Password:') !!}
              <input class="form-control" placeholder="Password" name="password" id="password" type="password">
            @if(Route::currentRouteName() == 'user.edit')
                <div class="alert alert-info">
                  <span class="fa fa-info-circle"></span> Leave the password field blank if you wish to keep it the same.
                </div>
            @endif
        </div>
        @else
        <div class="form-group col-sm-12">
        {!! Form::label('password', 'Password:') !!}
        {{ Form::password('password', array('class' => 'form-control','placeholder'=>'Password')) }}

        </div>
        @endif




<div class="form-group col-sm-12">
    @if(!empty($user->photo))
	<img src="{!! url($user->photo) !!}" width="100" height="100">
@endif	
</div>


<div class="form-group col-sm-12">
    {!! Form::label('photo', 'Photo:') !!}
    {!! Form::file('photo', null, ['class' => 'form-control']) !!}
</div>





<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Update', ['class' => 'btn btn-primary']) !!}
    <a href="{!! url('admin') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/admin/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Data
            <small>Admin</small>
        </h1>
    </section>
    <div class="clearfix"></div>
    <div class="clearfix"></div>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('admin.show_fields')
                    


                     <!-- <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#myModals">Edit</a> -->

                 		<a href="{!! route('admin.edit', [$user[0]->id]) !!}" class="btn btn-primary" >Edit</a>
                </div>
            </div>
        </div>
    </div>
@endsection



<!-- Modal -->
<div class="modal fade" id="myModals" tabindex="" role="dialog"  aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Profile</h4>
      </div>
      <div class="modal-body">
        	<div class="form-group">
			    {!! Form::label('name', 'Nama:') !!}
			    {!! Form::text('name', $user[0]->name, ['class' => 'form-control']) !!}
			</div>
			<div class="form-group">
			    {!! Form::label('email', 'Email:') !!}
			    {!! Form::text('email', $user[0]->email, ['class' => 'form-control']) !!}
			</div>
			<div class="form-group">
			    {!! Form::label('phone', 'Phone:') !!}
			    {!! Form::text('phone', $user[0]->phone, ['class' => 'form-control']) !!}
			</div>
			<div class="form-group">
			    {!! Form::label('address', 'Address:') !!}
			    {!! Form::textarea('address', $user[0]->address, ['class' => 'form-control']) !!}
			</div>
		

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" onclick="SimpanProfile();" class="btn btn-primary">Simpan</button>
      </div>
    </div>
  </div>
</div>

resources/views/admin/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Photo:') !!}
    <p><img width="50" height="50" src="{!! $user[0]->photo !!}"></p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Nama:') !!}
    <p>{!! $user[0]->name !!}</p>
</div>


<div class="form-group">
    {!! Form::label('type_id', 'Email:') !!}
    <p>{!! $user[0]->email !!}</p>
</div>

<div class="form-group">
    {!! Form::label('type_id', 'Phone:') !!}
    <p>{!! $user[0]->phone !!}</p>
</div>

<!-- Address Field -->
<div class="form-group">
    {!! Form::label('address', 'Address:') !!}
    <p>{!! $user[0]->address !!}</p>
</div>

<div class="form-group">
    
       <table class="table table-responsive">
           <thead>
                <th>Photo</th>
                <th>Bank</th>
                <th>No Rekening</th>
                <th>Atas Nama</th>
                <th>Action</th>
           </thead>
           @foreach($bank as $bank)
           <tr>
              
                <td><img width="100" height="50" src="{!! $bank->image !!}"> </td>
                <td>{!! $bank->name !!}</td>
                <td>{!! $bank->account_number !!}</td>
                <td>{!! $bank->account_name !!}</td>
                <td>
                  
                  {!! Form::open(['route' => ['bank.destroy', $bank->id.''.'?type=admin'], 'method' => 'delete']) !!}
                <div class='btn-group'>
                   
                    <a href="{!! url('bank/'.$bank->id.'/edit?type=admin') !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
                </td>
           </tr>
           @endforeach
       </table> 
    
</div>